### ISSUE TITLE
Enabling ThinLTO

### ISSUE THREAD

**Issue by Skylion007** [mosra/toolchains#15]
When enable IPO for CMake, it defaults to ThinLTO on Clang which is much faster than normal LTO, but does occasionally run into issues. #14 brings us part of the way there and immediately solves the issue with Full LTO. 
One of the main blockers is a bug in the EMSDK Toolchain here: https://github.com/emscripten-core/emscripten/issues/12763 but there is also a workaround in the first issue about the naming of the archive libraries and object files. We should look into solving that in this toolchain as well.

**Comment by mosra** [comment]
#14 is merged now, the linked Emscripten issue is marked as solved now as well. I tried changing the flags from `-flto` to `-flto=thin` and everything worked well, giving a minor speed boost as well. Linking `CorradeVersionTest` went from 4.8 s with `-flto` to 3.8 with `-flto=thin`. Not great, not terrible.

So I guess nothing left to do here.
