### ISSUE TITLE
DEFIEND != DEFINED

### ISSUE THREAD

**Issue by lecopivo** [mosra/toolchains#3]
https://github.com/mosra/toolchains/blob/d7beaeddc68c5ee07603f1c87cef4d4323c6f0f4/generic/Emscripten-wasm.cmake#L17

Hi, 
there is a typo 
`    if(DEFIEND ENV{EMSCRIPTEN})`
should be
`    if(DEFINED ENV{EMSCRIPTEN})`
Best,
Tomas

**Comment by mosra** [comment]
Ugh, apparently I managed to make a syntax error, revert it, revert the revert and make a typo in an attempt to fix the reverted revert, all in a single line of code. Amazing and/or awful. Fix is in 555f957757d32811ef29026c4eca60d6f6b8239c.

Thanks!

... "lečo pivo"? :)

**Comment by lecopivo** [comment]
I don't even want to know what happened there :D.

... správně ;)
